version: "3"
services:
  cron:
    container_name: piscan_cron
    build:
      context: .
      dockerfile: cron/Dockerfile
    volumes:
      - ${LOGS_PATH}:/logs
    command: cron -f
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine
    command: --port 6000
    container_name: piscan_redis
    restart: unless-stopped

  app:
    privileged: true
    depends_on:
      - redis
    container_name: piscan
    command: /bin/sh -c "/pi_scan/scripts/entrypoint.sh"
    build: .
    restart: unless-stopped
    ports:
      - "6363:8000"
    volumes:
      - ${DB_PATH}:/pi_scan/database
      - ${LOGS_PATH}:/pi_scan/logs
      - ${FILES_PATH}:/pi_scan/files
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
